# Define just service names
# this is a list of services will route by gateway
# write service names in uppercase like below, like Eureka service names
services:
  names: AUTH-SERVICE,PRODUCT-SERVICE,SETTLEMENT-SERVICE,CART-SERVICE